title: 'Product & Innovation'
updated_by: 071d1a69-4df7-4eb1-91d6-d67964b1264e
updated_at: 1693361834
blueprint: topic
seo_description: 'Keep up to date on the latest products and innovation in digital signage and merchandising from Coates Group. Read on to learn more.'
seo_noindex: false
seo_nofollow: false
seo_canonical_type: entry
sitemap_change_frequency: weekly
sitemap_priority: 0.5
