data:
  alt: 'Drive-thru solutions and Order confirmation units for restaurants designed by Coates Group Australia'
size: 279381
last_modified: 1691412278
width: 3000
height: 2113
mime_type: image/jpeg
duration: null
