tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              localizable: true
          -
            handle: one_click_content_translation
            field:
              display: 'One-click Content Translation'
              type: one_click_content_translation_inputs
              listable: hidden
              visibility: hidden
              localizable: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
              localizable: false
title: 'Product Type'
