title: Products
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: true
      listable: hidden
      display: Title
  -
    handle: text
    field: common.text_plain
    config:
      display: Text
  -
    handle: block_type
    field:
      options:
        panels: Panels
        carousel: Carousel
        drive_thru: 'Drive Thru'
      default: panels
      type: button_group
      display: 'Block Type'
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
      localizable: false
  -
    handle: image
    field: common.image
    config:
      mode: grid
      if:
        block_type: 'equals drive_thru'
  -
    handle: products
    field:
      fields:
        -
          handle: product
          field:
            max_items: 1
            mode: default
            type: entries
            collections:
              - products
              - hardware
            localizable: true
            listable: false
            display: Product
            replicator_preview: false
            instructions: 'Select from the [Products](/cp/collections/products) or [Hardware](/cp/collections/hardware) collections.'
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
        -
          handle: text
          field: common.text_plain
          config:
            display: Text
      mode: stacked
      min_rows: 1
      add_row: 'Add product'
      reorderable: true
      type: grid
      localizable: true
      listable: hidden
      display: Products
      instructions: 'Display Product content or add your own title and text.'
      replicator_preview: false
      instructions_position: above
      visibility: visible
      fullscreen: true
      hide_display: false
