title: Products
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: true
      listable: hidden
      display: Title
  -
    handle: text
    field: common.text_plain
    config:
      display: Text
  -
    handle: block_type
    field:
      options:
        grid: Grid
        carousel: Carousel
        drive_thru: 'Drive Thru'
      default: grid
      type: button_group
      display: 'Block Type'
      icon: button_group
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: image
    field: common.image
    config:
      mode: grid
      if:
        block_type: 'equals drive_thru'
  -
    handle: products
    field:
      fields:
        -
          handle: focal_point
          field:
              display: 'Focal Point'
              type: focalpoint
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              always_save: false
              assets_field_handle: image
        -
          handle: product
          field:
            max_items: 1
            mode: default
            type: entries
            collections:
              - products
            localizable: true
            listable: false
            display: Product
            replicator_preview: false
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
        -
          handle: text
          field: common.text_plain
          config:
            display: Text
      mode: stacked
      min_rows: 1
      add_row: 'Add product'
      reorderable: true
      type: grid
      localizable: true
      listable: hidden
      display: Products
      replicator_preview: false
      instructions_position: above
      visibility: visible
      fullscreen: true
      hide_display: false
