title: 'Product'
fields:
  -
    handle: title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: headline
    field:
      input_type: text
      antlers: false
      display: Headline
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: text
    field: common.text_plain
    config:
      display: Text
  -
    import: buttons
  -
    handle: image
    field: common.image
    config:
      mode: grid
      display: Image
      width: 50
      validate:
        - required
