title: Products
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: true
      listable: hidden
      display: Title
  -
    handle: products
    field:
      mode: default
      create: true
      collections:
        - products
      display: Products
      type: entries
      icon: entries
      listable: hidden
      instructions_position: below
      instructions: 'Select entries or leave empty to show all.'
      visibility: visible
      always_save: false
