title: 'Product Features'
fields:
  -
    handle: media_type
    field:
      options:
        animation: Animation
        image: Image
      default: animation
      type: button_group
      display: 'Media Type'
      icon: button_group
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: animation
    field: common.image
    config:
      container: animations
      restrict: true
      display: 'Lottie Animation'
      instructions_position: below
      width: 50
      instructions: 'This should be a *.json* file.'
      if:
        media_type: 'equals animation'
  -
    handle: frames
    field:
      input_type: text
      antlers: false
      type: text
      display: Frames
      icon: text
      instructions: 'Amount of frames from beginning to end.'
      listable: hidden
      instructions_position: below
      visibility: visible
      hide_display: false
      default: 30
      width: 25
      if:
        media_type: 'equals animation'
  -
    handle: reverse_frames
    field:
      default: false
      type: toggle
      display: 'Reverse Frames'
      icon: toggle
      width: 25
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: image
    field: common.image
    config:
      mode: grid
      width: 50
      folder: products
      if:
        media_type: 'equals image'
  -
    handle: size
    field: common.size
  -
    handle: features
    field:
      fields:
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
        -
          handle: text
          field: common.text_plain
          config:
            display: Text
        -
          handle: feature_position
          field:
            options:
              left: 'Left Side'
              right: 'Right Side'
            taggable: false
            push_tags: false
            multiple: false
            clearable: false
            searchable: true
            cast_booleans: false
            default: left
            type: select
            display: 'Feature Position'
            icon: select
            instructions: 'Show feature on the left or right side of the animation.'
            width: 50
            listable: hidden
            instructions_position: above
            visibility: visible
            hide_display: false
            replicator_preview: false
      mode: stacked
      add_row: 'Add feature'
      reorderable: true
      type: grid
      localizable: true
      listable: hidden
      display: Features
      replicator_preview: false
      instructions_position: above
      visibility: visible
      fullscreen: true
      hide_display: false
