title: 'Products'
fields:
  -
    handle: title
    field:
      input_type: text
      type: text
      localizable: true
      listable: hidden
      display: Title
  -
    handle: text
    field: common.text_plain
    config:
      display: Text
  -
    handle: block_type
    field:
      options:
        grid: 'Grid'
        carousel: Carousel
      default: grid
      type: button_group
      display: 'Block Type'
      icon: button_group
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
  -
    handle: products
    field:
      fields:
        -
          handle: product
          field:
            max_items: 1
            mode: default
            type: entries
            collections:
              - products
            localizable: true
            listable: false
            display: Product
            replicator_preview: false
        -
          handle: title
          field:
            input_type: text
            type: text
            localizable: true
            listable: hidden
            display: Title
            if:
              product: empty
        -
          handle: text
          field: common.text_plain
          config: 
            display: Text
            if:
              product: empty
      mode: stacked
      min_rows: 1
      add_row: 'Add product'
      reorderable: true
      type: grid
      localizable: true
      listable: hidden
      display: 'Products'
      replicator_preview: false
      instructions_position: above
      visibility: visible
      fullscreen: true
      hide_display: false
