title: Product
fields:
  -
    handle: product_type
    field:
      mode: select
      create: true
      taxonomies:
        - product_types
      type: terms
      display: Product Type
      max_items: 1
      icon: taxonomy
      listable: hidden
      instructions_position: above
      visibility: visible
      hide_display: false
      instructions: 'When to show this section.'
      width: 50
      if:
        root.show_product_types: 'equals true'
  -
    handle: title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: headline
    field:
      input_type: text
      antlers: false
      display: Headline
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: text
    field: common.text_plain
    config:
      display: Text
  -
    import: buttons
  -
    handle: images
    field: common.image
    config:
      mode: grid
      display: Images
      max_files: 0
      validate:
        - required
      folder: products
