title: 'Values Carousel'
fields:
  -
    handle: title
    field:
      input_type: text
      antlers: false
      display: Title
      type: text
      icon: text
      listable: hidden
      instructions_position: above
      visibility: visible
      always_save: false
  -
    handle: values
    field:
      mode: default
      type: entries
      collections:
        - values
      localizable: true
      listable: false
      display: Values
      replicator_preview: false
      instructions: 'Leave blank to show all Values.'
