title: Products
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              input_type: text
              localizable: true
              listable: true
              display: Title
              validate:
                - required
      -
        display: 'Page builder'
        fields:
          -
            import: page_builder
  sidebar:
    display: Sidebar
    sections:
      -
        display: Meta
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              generate: true
              listable: hidden
              display: Slug
              validate:
                - required
