title: Products
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              input_type: text
              localizable: true
              listable: true
              display: Title
              validate:
                - required
          -
            handle: headline
            field:
              input_type: text
              antlers: false
              type: text
              display: Headline
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              localizable: true
          -
            handle: text
            field: common.text_plain
            config:
              display: Text
          -
            handle: image
            field: common.image
            config:
              mode: grid
              listable: true
              folder: products
              width: 50
          -
            handle: hero_image
            field: common.image
            config:
              mode: grid
              display: 'Hero Image'
              folder: products
              width: 50
          -
            handle: enable_hero
            field:
              default: false
              type: toggle
              display: 'Enable Hero'
              icon: toggle
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              instructions: 'Replace page header with hero.'
              localizable: false
          -
            handle: show_product_types
            field:
              default: false
              type: toggle
              display: 'Show Product Types'
              instructions: 'Add tabs to show or hide product type sections.'
              icon: toggle
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              width: 50
              localizable: false
          -
            handle: overlay_opacity
            field:
              min: 0
              max: 100
              step: 5
              default: 100
              append: '%'
              type: range
              display: 'Overlay Opacity'
              icon: range
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              localizable: false
      -
        display: 'Page builder'
        fields:
          -
            import: page_builder
          -
            handle: one_click_content_translation
            field:
              display: 'One-click Content Translation'
              type: one_click_content_translation_inputs
              listable: hidden
              visibility: hidden
              localizable: false
  seo:
    display: SEO
    sections:
      -
        display: Basic
        instructions: 'Basic SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_basic'
      -
        display: Advanced
        instructions: 'Advanced SEO settings.'
        fields:
          -
            import: 'statamic-peak-seo::seo_advanced'
      -
        display: 'Open Graph'
        instructions: 'Open Graph meta tags for social sharing.'
        fields:
          -
            import: 'statamic-peak-seo::seo_open_graph'
      -
        display: Sitemap
        instructions: 'Sitemap configuration.'
        fields:
          -
            import: 'statamic-peak-seo::seo_sitemap'
      -
        display: 'JSON-ld Schema'
        instructions: 'Custom JSON-ld schema objects.'
        fields:
          -
            import: 'statamic-peak-seo::seo_jsonld'
  sidebar:
    display: Sidebar
    sections:
      -
        display: Meta
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              generate: true
              listable: hidden
              display: Slug
              validate:
                - required
          -
            handle: nav_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Nav Title'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              localizable: true
          -
            handle: product_types
            field:
              type: terms
              taxonomies:
                - product_types
              display: 'Product Types'
              mode: default
              if:
                show_product_types: 'equals true'
              instructions_position: above
              listable: true
              visibility: visible
              create: true
              hide_display: false
              localizable: true
