title: Products
tabs:
  main:
    display: Main
    sections:
      -
        display: General
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              input_type: text
              localizable: true
              listable: true
              display: Title
              validate:
                - required
          -
            handle: headline
            field:
              input_type: text
              antlers: false
              type: text
              display: Headline
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: text
            field: common.text_plain
            config:
              display: Text
          -
            handle: enable_hero
            field:
              default: false
              type: toggle
              display: 'Enable Hero'
              icon: toggle
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              instructions: 'Replace page header with hero.'
      -
        display: 'Page builder'
        fields:
          -
            import: page_builder
  sidebar:
    display: Sidebar
    sections:
      -
        display: Meta
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              generate: true
              listable: hidden
              display: Slug
              validate:
                - required
          -
            handle: image
            field: common.image
            config:
              mode: grid
