title: Products
template: products/show
layout: layout
mount: d70deed0-6959-4ec0-97a2-75d120b8899e
revisions: false
route: '/{mount}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
inject:
  enable_hero: true
  hero_type: product
structure:
  root: false
  max_depth: 1
